language: php

env:
    - SYMFONY_DEPS_VERSION=2.3
    - SYMFONY_DEPS_VERSION=2.4
    - SYMFONY_DEPS_VERSION=2.5
    - SYMFONY_DEPS_VERSION=2.6
    - SYMFONY_DEPS_VERSION=2.7

before_script:
    # symfony/*
    - sh -c "if [ '$SYMFONY_DEPS_VERSION' = '2.7' ]; then sed -i 's/~2.3/2.7.*@dev/g' composer.json; composer update --dev --prefer-source; fi"
    - sh -c "if [ '$SYMFONY_DEPS_VERSION' = '2.6' ]; then sed -i 's/~2.3/2.6.*@dev/g' composer.json; composer update --dev --prefer-source; fi"
    - sh -c "if [ '$SYMFONY_DEPS_VERSION' = '2.5' ]; then sed -i 's/~2.3/2.5.*@dev/g' composer.json; composer update --dev --prefer-source; fi"
    - sh -c "if [ '$SYMFONY_DEPS_VERSION' = '2.4' ]; then sed -i 's/~2.3/2.4.*@dev/g' composer.json; composer update --dev --prefer-source; fi"
    - sh -c "if [ '$SYMFONY_DEPS_VERSION' = '2.3' ]; then sed -i 's/~2.3/2.3.*@dev/g' composer.json; composer update --dev --prefer-source; fi"
    - composer install --dev --prefer-source

script: phpunit

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php: hhvm
